### PR TITLE
Fix load requests to send load type messages. Closes #182

### LINKED ISSUE #182: Client send put instead of load requests
**BUG REPORT**

When generating messages to send to cache server the client generate PUT type messages even for LOAD requests.
Load messages should be sent instead.

### PR DESCRIPTION
**Pull request by diegosalvi**
Change Message to the right type when generating LOAD messages instead of sending PUT messages (and changing expected cache behaviour)

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Review by eolivelli — CHANGES_REQUESTED** [review]
Please add test cases.

Please note that even if this looks like a goos fix the impact in production may be non negligible.

We must bump the version, it is not a minor change

**Comment by diegosalvi** [comment]
Added a test for put&load interactions.
I know this is just a one line modify but can have many side effects from client perspective.

**Comment by diegosalvi** [comment]
@eolivelli before releasing this I know we'll need a major version bump.

**Review by dmercuriali — APPROVED** [review]
lgtm

**Comment by dmercuriali** [comment]
@eolivelli are you fine with the changes?

**Pull request merged**
