### PR TITLE
upgraded to target 17

### PR DESCRIPTION
**Pull request by dmercuriali**
upgraded target and source version to java 17.
java 15 dropped package `sun.security.x509` so dependency to `bouncycastle` is now required

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by eolivelli** [comment]
is the TCK still passing ?

**Comment by eolivelli** [comment]
is it really worth to change the target version to 17 ? why can't we keep 8 ?

**Comment by eolivelli** [comment]
making it work on JDK17 is fine, but removing support for 8 is a breaking change for users, it will require a major version upgrade.
I would do it only if it adds some value

**Comment by dmercuriali** [comment]
@eolivelli sorry didn't see the comments.

We havo no strong requirements to move on jdk17, I'll revert the `target` changes keeping the dependency fix

**Pull request merged**
